refactor: layout
In-N-Out-Dev/PortfolioHub pull request #19
Opened 2023-04-29 11:21 UTC by HojinAn

## 세부 사항

- footer padding 값 수정
- stack button semantic, 크기에 알맞게 수정
- 합의 한대로 Divider 기준 margin을 divider marginTop, marginBottom을 통해 조정하도록 변경하고 적용했습니다.

## 기타 질문 및 특이 사항

- @Junghoon-P 피그마 레이아웃과 맞춰서도 Divider 60px(6rem)으로는 알맞지 않을 것 같아서 번거로워도 section마다 margin-bottom 수정하면 감사하겠습니다! :)
- @somangoi 아까 이야기한대로 `ListCard` 내의 Divider에 margin 추가했어요!
- 피그마 변경에 맞춰 Divider의 색상을 MAIN_FONT 색으로 변경했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2023-05-09 10:44 UTC, Junghoon-P approved these changes
한번 정리해주셔서 감사합니다. LGTM~!

2023-05-09 11:04 UTC, Junghoon-P requested changes
`CareerContents`와 `ProjectContents`에서 Warning: Each child in a list should have a unique "key" prop. 경고가 나오는데 key 추가만 적용 부탁드립니다!

2023-05-09 11:25 UTC, Junghoon-P requested changes

2023-05-09 11:25 UTC, Junghoon-P commented on src/components/portfolio/Portfolio.tsx
> +        marginBottom={10}
<img width="220" alt="스크린샷 2023-05-09 오후 8 23 27" src="https://github.com/In-N-Out-Dev/PortfolioHub/assets/77766769/c2bbbd3c-6160-443e-900a-596824313a40">

지금 모든 컴포넌트의 `Divider`가 마진 상하 100px로 적용되어 있는데 피그마를 확인해보면 70px로 보여지는데 확인 부탁드립니다!

2023-05-09 13:55 UTC, HojinAn commented on src/components/portfolio/Portfolio.tsx
> +        marginBottom={10}
오잉 피그마에 100px로 되어 있지 않나요??
<img width="574" alt="image" src="https://github.com/In-N-Out-Dev/PortfolioHub/assets/47904304/fe53440d-8dfc-4947-81cd-77799d5de5fa">

2023-05-11 12:48 UTC, somangoi approved these changes
정훈님 코멘트만 해결된다면 LGTM! 고생하셨습니다

2023-05-14 10:48 UTC, Junghoon-P approved these changes

2023-05-14 10:48 UTC, merged