refactor: common Card components & nav action
In-N-Out-Dev/PortfolioHub pull request #21
Opened 2023-05-23 14:53 UTC by HojinAn

## 세부 사항

- 반응형을 위해서 Section에 해당하는 Card 컴포넌트를 추상화했습니다. 그냥 Card로 명명하기에는 기본 padding이 들어가서 SectionCard로 명명했습니다. 그리고 기존 InfoCard, ListCard를 알맞게 적용했습니다.
- 기존 Divider가 불필요한 element를 발생시킨다고 판단하고 Section border top으로 설정했습니다.
- Nav action 오류도 덤으로 수정~

## 기타 질문 및 특이 사항

-
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2023-05-31 07:16 UTC, Junghoon-P approved these changes

2023-05-31 07:35 UTC, Junghoon-P requested changes
test

2023-05-31 07:35 UTC, Junghoon-P commented on src/components/career/CareerContents.tsx
>  const CareerContents = () => {
test

2023-06-01 12:19 UTC, somangoi approved these changes

2023-06-10 05:14 UTC, Junghoon-P approved these changes

2023-06-10 05:14 UTC, merged