Responsive/Portfolio, Contact, Footer
In-N-Out-Dev/PortfolioHub pull request #27
Opened 2023-07-09 13:03 UTC by HojinAn

## 세부 사항

- mobile view에서 github, insta 등등은 svg로 사용해야하는데, 파일 아직 못구해서 피그마에서 png로 추출해서 적용했습니다~ vite에서 svg 사용하려면 svgr 라이브러리 추가로 설치해야합니다!
- 각종 반응형 추가했습니다
-

## 기타 질문 및 특이 사항

- 없습니다~
- 애니메이션은 차차 좀 할게요,,,ㅋㅋ

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2023-07-09 13:09 UTC, HojinAn commented on src/components/common/Footer.tsx
> +  }
코드 스타일 다른 부분과 통일할 것

2023-07-09 13:09 UTC, HojinAn commented on src/components/portfolio/gallery/PortfolioGallery.tsx
> +  })();
memo로 최적화 가능

2023-07-09 13:09 UTC, HojinAn commented on src/components/portfolio/gallery/PortfolioGallery.tsx
> +  })();
재사용 되지 않으면, 그냥 styled 코드 안에서 처리할 수 있지 않나? 어디에서 처리가 더 성능적으로 좋은지 생각해보기

2023-07-09 13:14 UTC, Junghoon-P commented on src/components/common/Footer.tsx
> +  }
ditto

2023-07-09 13:15 UTC, Junghoon-P commented on src/components/portfolio/gallery/PortfolioGallery.tsx
> +  })();
성능 측면에서는 저도 더 공부해봐야 하는데 기본적인 흐름상 styled 안에서도 처리 가능하지 않을까요?

2023-07-09 13:15 UTC, Junghoon-P approved these changes
LGTM

2023-07-09 13:16 UTC, HojinAn commented on src/components/portfolio/gallery/PortfolioGallery.tsx
> +  })();
아무래도 styled가 static하니까 그러겠죠??

2023-07-11 22:45 UTC, somangoi requested changes

2023-07-11 22:45 UTC, somangoi commented on src/components/contact/Contact.tsx
> +  }}
[CMT] 굿굿 이렇게 쓰는거 가독성 넘 좋네요

2023-07-11 22:45 UTC, somangoi commented on src/components/contact/ContactContents.tsx
> +          {isSmallDisplay ? <img src="/src/assets/img/Instagram.png" /> : 'Linkedin'}
[SUG] 사소하지만 링드인 공식 스펠이 LinkedIn 라서 수정해주시면 좋겠습니다!

2023-07-11 22:45 UTC, somangoi commented on src/components/portfolio/list/PortfolioItem.tsx
> +  font-family: 'Bebas Neue', cursive;
[SUG] cursive로 하면 메인 폰트 로드 전까지 이상한 필기체가 나와서 제가 이전에 수정한걸로 바꿔주시면 좋겠습니다.

```suggestion
  font-family: 'Bebas Neue', -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu,
    Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;```
```

2023-07-11 22:52 UTC, somangoi commented
앗 그리고 figma에서 export하실때 svg로 하면 안되나요?

2023-07-12 14:34 UTC, HojinAn commented
> 앗 그리고 figma에서 export하실때 svg로 하면 안되나요?

아 이게 svg로 추출해도 img 기반이더라고요 ㅋㅋ ㅠㅠ

2023-07-12 14:39 UTC, somangoi approved these changes

2023-07-12 14:39 UTC, merged