Layout/side bar and content
In-N-Out-Dev/PortfolioHub pull request #5
Opened 2023-03-26 06:48 UTC by somangoi

## 세부 사항
- 메인 페이지의 전체 레이아웃을 작성했습니다.
  - Nav bar를 추가했습니다.
  - Side nav를 추가했습니다.
  - Layout을 추가하고, grid로 메인 콘텐츠의 영역을 사이드바:콘텐츠 = 1:3으로 지정했습니다
  - screenshot
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/69243665/227760108-1e5cfd5b-5c9a-4515-b46c-3445501e2ca1.png">

## 기타 질문 및 특이 사항
- Mock content를 만들어 전체적인 페이지의 구조를 파악할 수 있게 했습니다.(해당 코드는 자유롭게 추후에 수정해주세요)
- 해당 레이아웃에서는 반응형 UI를 완벽히 고려하지 않았습니다. 나중에 반응형 디자인이 추가되면 적용하겠습니다!
- eslint가 적용되지 않아 import 순서가 컨벤션과 맞지 않을 수 있습니다! 이 부분 나중에 도움 받을 수 있으면 좋겠습니다.
- 레이아웃은 @Junghoon-P 님의 도움을 받아 작성하였는데, 혹시 논의된 부분에서 벗어나는 지점이 있다면 코멘트 해주시면 감사하겠습니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2023-03-26 10:26 UTC, HojinAn commented on src/components/Container.tsx
> +  background-color: lightsalmon;
후에 바꿀 수 있어도 theme과 상응하기 위해서 theme에 추가하고 사용하는건 어떨까요??

2023-03-26 10:26 UTC, HojinAn commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
이건 나중에 이야기해봐야할거 같긴한데 
1. components/index.ts에서 각 컴포넌트들 다 export하는거랑 
2. 이렇게 일일이 import 받는거랑 뭐가 좋을까요? 

사실 Nav, SideNav랑 Layout 상대 위치가 바뀔거 같지는 않지만

---

그리고 차라리 `components/layout`에다가 `Layout.tsx`랑 `nav/` 이하 레이아웃 관련 컴포넌트들을 두는건 어떨까요?

@somangoi  @Junghoon-P

2023-03-26 10:26 UTC, HojinAn commented on src/App.tsx
> +  return <Layout content={<Container />} />;
- [ ] children으로 안하고 content props로 정한 이유가 있을까요??

2023-03-26 10:26 UTC, HojinAn commented on src/components/common/Layout.tsx
> +const Layout = ({ content }: { content: JSX.Element }) => {
- [ ] type 설정은 나중에 하는거죠??

2023-03-26 12:16 UTC, Junghoon-P requested changes

2023-03-26 12:16 UTC, Junghoon-P commented on src/App.tsx
> +  return <Layout content={<Container />} />;
ditto 🤔

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/Container.tsx
> +  background-color: lightsalmon;
@HojinAn  어차피 저희가 구현한 컴포넌트들이 들어갈 자리라, 해당 컴포넌트들이 theme만 잘 적용하고 있으면 문제가 없을 것 같아요!

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
우선 저는 Common에 Layout 및 nav가 모두 들어가는게 맞다고 생각해요. layout 디렉토리를 추가로 만드는 것은 오히려 컴포넌트 폴더가 더 혼잡해지지 않을까요?

그리고 만일 그 해당 디렉토리마다 export하는 컴포넌트가 많다면 상황에 따라 1번처럼 index 만들어 관리하는게 어떨까요?
지금의 경우는 만드는게 좋을 것 같네요!

@somangoi  추가로 저희 절대경로 세팅했으니 import도 상대경로가 아닌 절대경로로 적용 부탁드립니다!

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +  grid-template-columns: 1fr 3fr;
grid 간만이군요! 👍 확실히 지금 구조는 grid가 더 효율적일 것 같아요!

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/nav/SideNav.tsx
> +const ContentWrapper = styled.div`
`ul > li` 로 마크업은 어떨까요? 제안입니다!😁

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/nav/SideNav.tsx
> +  background-color: lightblue;
아마 지금은 먼저 레이아웃 잡느라 배경색을 임의로 주신 것 같아요.
하지만 나중에 리팩토링을 줄이기 위해 위에 호진님 말처럼 theme을 적용하는게 어떨까요?
```suggestion
  color: ${({ theme }) => theme.colors.BACKGROUND};
```

2023-03-26 12:16 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +    <>
여기서 전체 뒷배경색을 지정하면 좋을 것 같아요.
`background-color: ${({ theme }) => theme.colors.BACKGROUND};`

2023-03-26 12:18 UTC, somangoi commented on src/components/Container.tsx
> +  background-color: lightsalmon;
background 색상을 말씀하시는거라면, 레이아웃 보시기 편하라고 예시로 넣은거고 꼭 삭제해야하는 코드이긴합니다! 주석을 달까유 @HojinAn

2023-03-26 12:23 UTC, somangoi commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
1. 절대경로 관련
  - 오 이게 auto로 임포트 되는 거는 절대경로로 세팅이 안되네요..? 원래 이런가요? @Junghoon-P 
2. 임포트 방식 관련
  - 또 index.ts 에서 임포트 하면 어떤 효용이 있을까요?
  - 그리고 우리처럼 작은 규모의 프로젝트에서 주로 그렇게 하는지 궁금하네요!
3. 디렉토리 관련
  - nav는 nav 폴더로 빼는게 맞을 것 같아요!
  - layout은 폴더로 둬도 상관없을 것 같긴한데 저는 layout 자체가 component가 될 수 있는지도 약간 헷갈리기도 하네요..? 애초에 components 폴더에서 뺄까도 고민했습니다. 어떻게 생각하시나요? 혹시 비슷한 경로로 설정한 프로젝트르 보신적이 있나요?

2023-03-26 12:24 UTC, somangoi commented on src/App.tsx
> +  return <Layout content={<Container />} />;
props 컨벤션이 따로 있나요? 저는 뭔가 시멘틱하게 하고 싶었습니다만

2023-03-26 12:24 UTC, somangoi commented on src/components/nav/SideNav.tsx
> +const ContentWrapper = styled.div`
쪼아용

2023-03-26 12:25 UTC, somangoi commented on src/components/nav/SideNav.tsx
> +  background-color: lightblue;
요거는 배경색 자체가 사라질 건데 theme으로 적용하면 리팩토링이 줄어드는 효과가 있나요?

2023-03-26 12:25 UTC, somangoi commented on src/components/common/Layout.tsx
> +    <>
좋습니당

2023-03-26 12:26 UTC, somangoi commented on src/components/common/Layout.tsx
> +const Layout = ({ content }: { content: JSX.Element }) => {
type설정은 어떤걸 말씀하시는건가요? 혹시 type이나 interface로 빼는걸 말씀하시는걸까요?

2023-03-26 12:26 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
> 1. 절대경로 관련
> 
> * 오 이게 auto로 임포트 되는 거는 절대경로로 세팅이 안되네요..? 원래 이런가요? @Junghoon-P
> 
> 2. 임포트 방식 관련 @HojinAn
> 
> * 또 index.ts 에서 임포트 하면 어떤 효용이 있을까요?
> * 그리고 우리처럼 작은 규모의 프로젝트에서 주로 그렇게 하는지 궁금하네요!
> 
> 3. 디렉토리 관련
> 
> * nav는 nav 폴더로 빼는게 맞을 것 같아요!
> * layout은 폴더로 둬도 상관없을 것 같긴한데 저는 layout 자체가 component가 될 수 있는지도 약간 헷갈리기도 하네요..? 애초에 components 폴더에서 뺄까도 고민했습니다. 어떻게 생각하시나요? 혹시 비슷한 경로로 설정한 프로젝트르 보신적이 있나요?

1. 같은 디렉토리에 있는 경우에는 auto 임포트가 상대경로로 들어가더라고요 ㅠ 그래서 저는 그 부분만 한번 바꿔줍니다!
2. 이건 저희끼리 정하면 되는 부분이긴한데 정말 스타일이라 아마 가독성을 얼마큰 챙기냐인 것 같아요!
3. 아마 2번이랑 이어질 것 같은데, 저희는 작은 규모의 프로젝트니까 common으로 어느정도 커버되지 않을까요? 아까 디코에서 말했던 것처럼 현재 layout이 container까지 포함하고 있는 것이 아닌 children으로 이어지는 경우라면, components 폴더에 저는 속한다고 생각해요.

2023-03-26 12:29 UTC, HojinAn commented on src/components/Container.tsx
> +  background-color: lightsalmon;
주석도 좋아요 ㅎㅎ 혹시 까먹을까봐요!

2023-03-26 13:07 UTC, HojinAn commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
@Junghoon-P

저는 common components는 Input, Button 같은 애들이고 Header, Footer, Nav 같은 애들은 레이아웃 요소라고 생각해서요! 그래서 layout 폴더로 빼는게 더 의미에 맞다고 생각해요 아니면 common에서라도 빼던가?ㅎㅎ

<img width="983" alt="image" src="https://user-images.githubusercontent.com/47904304/227776713-bb5fad6c-a558-497c-a25a-2e18525e3920.png">

_출처: https://www.w3schools.com/css/css_website_layout.asp_

@somangoi 

![image](https://user-images.githubusercontent.com/47904304/227777377-57f337a3-0511-4e69-b9fe-ef0ba8edbaab.png)

사실 제가 이렇게 했어서..ㅎ 뭔가 common 컴포넌트 | ui용 컴포넌트(공통 활용한 UI만을 그리는 컴포넌트들) | layout 컴포넌트(Header, Footer, Main 등 큰 레이아웃 용)랑 분리하는게 더 의미가 와닿더라고요 전 

layout을 아예 밖으로 빼는 것도 좋은 생각 같아요 전!

2023-03-26 13:08 UTC, somangoi commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
1, 2번 코멘트 감사합니다!
3번은 조금 고민해보았는데, 레이아웃이 container말고도 nav, footer등등 페이지 구성을 담당하고 있어서 코드리뷰 반영하면서 pages 폴더를 만들어보았어요. 이게 더 직관적이고 오해의 소지는 적은 것 같고, 그리고 리액트 공식문서에서는 이런 디렉토리를 예시로 많이 들고 있어서 이렇게 해보았는데요. 아까 디코에서 논의한 내용과 다르기도 하고 .. 또 혹시 아니다 싶으시면 보시고 말씀해주세요!

2023-03-26 13:10 UTC, HojinAn commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
@somangoi  
2. 사실 빌드 등에서 이점이 있는지는 모르겠어요 그냥 보기에 편하다 정도?

![image](https://user-images.githubusercontent.com/47904304/227777835-9fdf0fdd-587d-4cb1-bc74-ee5020f87588.png)

이런식으로 하면 각 컴포넌트 출처가 분명해서 좋았어요 전 ㅎㅎ

2023-03-26 13:22 UTC, HojinAn commented on src/App.tsx
> +  return <MainPage childElement={<Container />} />;
```suggestion
  return ( 
    <MainPage>
      <Container />
    </MainPage>
  );
``` 
요거를 말한거였어요!

2023-03-26 13:24 UTC, HojinAn commented on src/App.tsx
> +  return <Layout content={<Container />} />;
https://github.com/In-N-Out-Dev/PortfolioHub/pull/5#discussion_r1148553989
요 얘기였습니당 ㅎㅎ

2023-03-26 15:02 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
> 1, 2번 코멘트 감사합니다! 3번은 조금 고민해보았는데, 레이아웃이 container말고도 nav, footer등등 페이지 구성을 담당하고 있어서 코드리뷰 반영하면서 pages 폴더를 만들어보았어요. 이게 더 직관적이고 오해의 소지는 적은 것 같고, 그리고 리액트 공식문서에서는 이런 디렉토리를 예시로 많이 들고 있어서 이렇게 해보았는데요. 아까 디코에서 논의한 내용과 다르기도 하고 .. 또 혹시 아니다 싶으시면 보시고 말씀해주세요!

https://github.com/In-N-Out-Dev/PortfolioHub/pull/8#discussion_r1148552188 이 코멘트에 달았던 내용이랑 유사하지만 좀 더 풀어서 이야기 해보겠습니다.

먼저 저희의 기획 목적도 함께 고려해보면 좋을 것 같습니다. 현재 제안해주신 pages 디렉토리 같은 경우에는 만일 저희가 라우터를 사용한다면 활용도가 많을 것 같지만, 현재 단일페이지 프로젝트다 보니 오히려 더 헷갈리게 할수도 있을 것 같습니다. 또한 개발자들을 위한 서비스이다 보니 이제는 `pages`의 네이밍이 `next.js`의 보편화로 객관성을 많이 잃었다고도 개인적으로 생각합니다.

하지만 어디까지나 제 개인적인 의견이라 위의 제 PR에 코멘트도 한번 확인해주시고 생각이 다르시다면 코멘트 부탁드립니다~!😉

2023-03-26 15:15 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
폴더링은 사실 저는 사전에 저희가 초기세팅때 합의했었다고 생각했는데 이해한 방향이 다들 조금 다른 것 같습니다. layouts에 대한 의견은 위의 코멘트를 참고해주시고 https://github.com/In-N-Out-Dev/PortfolioHub/pull/5#discussion_r1148551916 @HojinAn 여기서 호진님이 보여주신 폴더링에 대해 추가적으로 코멘트를 달겠습니다.

먼저 저는 컴포넌트 디렉토리안에서 공용 부분을 최대화 하는 것도 중요하지만 그만큼 반대인 해당 컴포넌트에서만 사용할 부분에 대해 분리고 알아보기 쉬운 것도 중요하다고 생각합니다. 
> 아마 "호진님의 폴더링 + pages 디렉토리"의 조합이 제가 컴포넌트 디렉토리안에서 제안드리는 방법과 유사할 것 같습니다. 

폴더링을 보여주신 이미지처럼 진행한다면 먼저 우려되는 부분은 각각의 폴더에서 특정 컴포넌트의 파일을 찾기 어려울 것 같다는 생각입니다. 이를 방지하기 위해 아마 파일명이 점점 더 길어질 것이라 생각하고, 그 네이밍에 있어서도 각자 3인의 스타일이 조금씩은 다를 것이라 예상하여 오히려 더 혼잡 해질 것 같습니다.

기획적인 얘기가 다시 나오지만, 저희의 프로젝트 목적을 생각해 본다면 이 레포를 저희가 아닌 다른 개발자들이 보게될 것이고 이를 사용할 것입니다. 그렇다면 그들이 저희의 프로젝트를 입맛에 맞게 커스텀하고 싶다면 각각의 섹션별로 디렉토리가 나뉘어 있는게 보다 이해하기 쉽지 않을까요? 이 점을 고려하여 저는 폴더링을 아래의 이미지처럼 진행하였습니다.
<img width="199" alt="스크린샷 2023-03-27 오전 12 13 25" src="https://user-images.githubusercontent.com/77766769/227785267-74c1b764-0a4e-4232-8599-962a0d204daa.png">

만일 폴더링이 아닌 `Container` 컴포넌트의 네이밍에 대해 논의를 희망하신다면 이미 제 PR에서 진행하고 있어서 해당 [PR](https://github.com/In-N-Out-Dev/PortfolioHub/pull/8#discussion_r1148568123)로 참고해주시면 좋을 것 같습니다.

2023-03-26 21:24 UTC, somangoi commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
의견감사합니다~! 사실 pages를 안써도 관계는 없으나 별로 중요한것은 아니니... 그냥 합의되는대로 따르겠슴다. 그런데 components의 의미가 무엇인지 생각해보면.. layout을 보통 넣나요? 재사용이 안되어서 오히려 헷갈리지는 않을까 걱정이 듭니다

2023-03-26 21:25 UTC, somangoi commented on src/App.tsx
> +  return <MainPage childElement={<Container />} />;
아 그러게요? ㅋㅋ 감사합니다.

2023-03-26 21:34 UTC, somangoi commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
그냥 레이아웃없이 레이아웃 파일에 있는 내용 app.tsx에 넣으면 안되나요? 오히려 뎁스만 많아진것 같기도 하고,,

2023-03-27 01:28 UTC, Junghoon-P commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
> 

이 부분은 layout의 활용방식에 따라 나뉠 것 같아요. 만일 정말 페이지 외부 마진값 또는 위치만 관리한다면 더욱 밀도 있는 프로젝트에서는 재사용이 가능할 것 같아요. 다만 이번 프로젝트에서는 저도 추가로 layout 디렉토리에 넣을 필요는 없을 것 같습니다. 
> 사실 레이아웃이 아니여도 정말 한번만 사용되는 컴포넌트도 있다보니, 저는 레이아웃도 컴포넌트의 공용폴더에 들어간다고 생각했던 것 같아요.

추가로 저는 app에서는 주로 view 역할만 최대한 보여주고자 했어서 아직은 components>common에 레이아웃을 넣어놓고 app에서 container를 감싸도 좋지 않을까?라는 생각입니다. 다만 뎁스 또는 다른 이유로 공감이 아직 어려우시다면 app에 넣어도 무방합니다.

폴더의 목적에 대해서 논의하는게 이렇게 다양하게 얘기할 수 있었군요! 재밌습니다

2023-03-28 11:29 UTC, HojinAn commented on src/components/common/Layout.tsx
> +import SideNav from '../nav/SideNav';
정훈님 의견처럼 각 섹션별로 컴포넌트 폴더링을 정리하는 것이 더 의미 있겠다는 생각이 듭니다! 저도 작업 #9 은 같은 방향으로 진행했습니다  
다만, layout 컴포넌트에 대한 정의가 서로 다른 것인지 layout 컴포넌트를 common에 넣는게 아직 와닿지가 않네요..🥲 어떤 이유로 common에 넣고자 하는지 다시 설명 부탁드려도 될까요? @Junghoon-P

2023-03-28 11:43 UTC, HojinAn commented on src/components/nav/Nav.tsx
> +const Nav = () => {
이 컴포넌트가 Nav보다는 Header가 되면 어떨까요?

2023-03-28 11:43 UTC, HojinAn commented on src/components/nav/Nav.tsx
> +const NavWrapper = styled.nav`
```suggestion
const HeaderWrapper = styled.header`
```
이런식으로 하고

2023-03-28 11:43 UTC, HojinAn commented on src/components/nav/Nav.tsx
> +const NavMenuWrapper = styled.div`
```suggestion
const NavMenuWrapper = styled.nav`
```

얘가 nav가 되는 건 어떨까요?

2023-03-28 11:43 UTC, HojinAn commented on src/components/common/Layout.tsx
> +const SectionWrapper = styled.div`
semantic 하게 가져가려면 section 정도 어떨까요??

2023-03-29 01:29 UTC, somangoi commented on src/components/common/Layout.tsx
> +const SectionWrapper = styled.div`
section은 그 자식요소에 있습니다

2023-03-29 01:30 UTC, somangoi commented on src/components/nav/Nav.tsx
> +const NavMenuWrapper = styled.div`
음...nav에 header를 로고로 포함시켜야할것 같은데요?

2023-03-29 01:32 UTC, somangoi commented on src/components/nav/Nav.tsx
> +const NavMenuWrapper = styled.div`
아 근데 생각해보니 navigation 기능이 없어서.. div로 바꾸겠습니다

2023-03-29 01:33 UTC, somangoi commented on src/components/Container.tsx
> +      <section>section 1</section>
섹션 의미를 생각해보면 우리 콘텐츠 전체를 한섹션으로 묶는게 별로인것 같아서 요렇게 하고 div로 묶었습니다 @HojinAn

2023-03-30 01:34 UTC, HojinAn approved these changes

2023-03-30 01:34 UTC, HojinAn commented on src/components/common/SideNav.tsx
> +const SideNavWrapper = styled.nav``;
아무래도 nav가 여기로 오는게 알맞은 거 같네요!

2023-03-30 01:34 UTC, HojinAn commented on src/components/Container.tsx
> +      <section>section 1</section>
확인 했습니다! 우리 콘텐츠 각각을 article로 하면 어떨까 생각도 드는데,, 우선 이렇게 가는 것도 좋습니다 ㅎㅎ

2023-04-02 15:34 UTC, Junghoon-P approved these changes
conflict만 해결하면 머지ㄱㄱ! LGTM~

2023-04-03 07:57 UTC, merged