feat: add Introduce section
In-N-Out-Dev/PortfolioHub pull request #8
Opened 2023-03-26 12:05 UTC by Junghoon-P

## 세부 사항
<img width="800" alt="스크린샷 2023-03-26 오후 8 53 41" src="https://user-images.githubusercontent.com/77766769/227774067-8b7068a4-e4df-4dab-ac4d-a4991ffabd16.png">
<img width="235" alt="스크린샷 2023-03-26 오후 8 53 47" src="https://user-images.githubusercontent.com/77766769/227774072-7c6c2e96-803a-4285-83a8-f74da9918b6c.png">

- `Introduce` 영역 UI 구현
 - `width` 100%로 설정하여 추후 `layout` 컴포넌트에 바로 적용 용이
 - 버튼 hover시 하이라이트 색상으로 변경
 - 공용컴포넌트`Divider`, `StackButton` 추가
   - `Divider` 마진/두께 props 세팅 => 기본 60px/2px
   - `StackButton` url 및 children 세팅
- 다크모드 대비 `theme` 활용 스타일링
- `introduceData`에서 mock 데이타 작성 및 연동

## 기타 질문 및 특이 사항
- `StackButton` url이 없을시 새창으로 이어지지는 않는데 시멘틱적으로 맞는지 고민입니다.
  - Ruseme를 보여주는 경우에는 url이 필요하지만 skills 같은 곳에서도 공통으로 사용할려면 div 또는 p 가 적합한게 아닐지 고민
    -  그렇다면 a, p 테그를 교차로 보여주는게 맞을지
  - 아니면 url이 없으면 페이지 이동은 하지 않으니 그냥 둘지 의견 부탁드립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge)

- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2023-03-26 13:18 UTC, somangoi requested changes

2023-03-26 13:18 UTC, somangoi commented on src/assets/Mail.tsx
> +const Mail = () => {
[SUG] MailIcon으로 컴포넌트 이름을 바꾸면 아이콘이라는걸 더 쉽게 알 수 있을 것 같습니다!

2023-03-26 13:18 UTC, somangoi commented on src/components/Container.tsx
>  const Container = () => {
[QN] 해당 PR과 관련이 없을 수 있지만, container라는 이름이 포괄적이어서 혹시 더 구체적으로 네이밍하면 어떨까요? 예시입니다만 BodyContentContainer라든지..

2023-03-26 13:18 UTC, somangoi commented on src/components/Container.tsx
> +  /* background-color: ${({ theme }) => theme.colors.HIGHTLIGHT}; */
[SUG] 여기 wrapper에는 명세에 색상이 안들어가있어서 지워도 될것 같습니다!

2023-03-26 13:18 UTC, somangoi commented on src/components/common/Divider.tsx
> +const Divider = ({ height = 2, margin = 60 }: DividerProps) => {
의견 반영 감사합니다

2023-03-26 13:18 UTC, somangoi commented on src/components/common/InfoCard.tsx
> +  font-family: 'Bebas Neue', cursive;
[SUG] 해당 폰트가 섹션 타이틀마다 들어가면 theme으로 적용가능할까요? 계속해서 쓸것같네요

2023-03-26 13:18 UTC, somangoi commented on src/components/common/StackButton.tsx
> +  :hover {
[QN] emotion에서는 &:hover이렇게 안써도 되나보죠? 신기방기

2023-03-26 13:18 UTC, somangoi commented on src/components/common/StackButton.tsx
> +  padding: 0.4rem 0.6rem;
[QN] 여기서만 rem 쓰는 이유가 궁금합니다! 이렇게 쓰면 폰트도 rem으로 통일시켜야 반응형대응에 유효할것 같아요.

2023-03-26 13:18 UTC, somangoi commented on src/components/introduce/IntroContents.tsx
> +  width: 600px;
[SUG] 여기서 너비 고정값이 필요할까요?

2023-03-26 13:18 UTC, somangoi commented on src/components/introduce/IntroContents.tsx
> +  font-size: 1.1rem;
[QN] 전체적으로 rem과 px이 섞여있는데, 이거에 대한 합의를 한번해보면 좋을 것 같네요! rem은 최상위 폰트 크기에 영향을 받아서 사용자가 브라우저 폰트 크기를 커스터마이징했다면 다 같이 영향을 받으니, 다른 것도 최대한 rem으로 쓰면 좋아서요! 혹시 다른 이유가 있다면 편히 말씀해주세요

2023-03-26 13:18 UTC, somangoi commented on src/styles/theme.tsx
> +const mode = 'dark' || 'light';
[QN] 안그래도 제 PR에 수정햇는데, 다크랑 라이트모드가 반대로 되어있는거 같더라고요..? 이거 혹시 제 PR확인해주실수 있나요?

2023-03-26 14:27 UTC, Junghoon-P commented on src/components/Container.tsx
>  const Container = () => {
음 이건 스타일 차이일 것 같아요.
제가 생각했던 의도는 저희가 포토폴리오 템플릿을 제공하는 프로젝트니까 좀 더 넓은 의미의 네이밍이 적합하지 않을까 생각했습니다.
components 디렉토리에서 홀로 나와있는 역할이다 보니 정말 모든걸 들고 있는 container다 라는 전달을 하고 싶었어요.
실제로 템플릿 업체들의 폴더링의 경우도 가능한 마크업 형식으로 네이밍을 많이 하더라고요!

2023-03-26 14:31 UTC, Junghoon-P commented on src/components/common/InfoCard.tsx
> +  font-family: 'Bebas Neue', cursive;
특정 타이틀에서만 적용될 폰트라 오히려 app에서부터 해당 폰트를 모르는게 좋지 않을까요?
만일 매번 import 해서 써야하는 번거로움이 예상되신다면 타이틀용 공용 컴포넌트로 분리해도 될 것 같아요.

2023-03-26 14:32 UTC, Junghoon-P commented on src/components/common/StackButton.tsx
> +  :hover {
styled은 안되나요..?

2023-03-26 14:35 UTC, Junghoon-P commented on src/components/common/StackButton.tsx
> +  padding: 0.4rem 0.6rem;
https://github.com/In-N-Out-Dev/PortfolioHub/pull/8#discussion_r1148553006 이 리뷰와 연관될 것 같은데 저도 코드 짜면서 고민인 부분이였습니다. 우선 여기서는 "해당 버튼의 테두리 크기를 픽셀값으로 고정하면 모바일에서 너무 두꺼워 보이지 않을까?" 라는 생각으로 rem을 사용했습니다. 저희가 사전에 통일하지 않았던 부분이라 @HojinAn  이번 PR에서 함께 정하면 좋을 것 같습니다.

2023-03-26 14:38 UTC, Junghoon-P commented on src/components/introduce/IntroContents.tsx
> +  width: 600px;
Wrap 내부의 `Contents`에서 줄바꿈 및 lineheight를 확인하기 위해서 고정값을 추가했습니다. 레이아웃 피알이 아직 정해진게 아니였어서 우선적으로 도입한 것도 있고, 만약 레이아웃으로 안잡힌다면 미디어쿼리로 대응할려고 했습니다. 현재 열려있는 레이아웃 PR이 머지된 후 판단하에 삭제 또는 반응형 대비할 예정입니다. 참고 부탁드립니다!

2023-03-26 14:40 UTC, Junghoon-P commented on src/components/introduce/IntroContents.tsx
> +  font-size: 1.1rem;
언급해주신대로 최상위 폰트 크기의 영향을 받다 보니 상대값으로 반응해야 하는 부분을 제 기준으로 판단해봤습니다. 오늘 회의때 말하는 것을 깜빡했어서 이번 PR을 통해 함께 정해보면 좋을 것 같아요. https://github.com/In-N-Out-Dev/PortfolioHub/pull/8#discussion_r1148552622 스래드에서 @HojinAn  함께 논의해보시죠!

2023-03-26 14:53 UTC, Junghoon-P commented on src/styles/theme.tsx
> +const mode = 'dark' || 'light';
@somangoi 소미님 PR 어디를 확인 요청주신걸까요..? 못 찾겠어서 해당 부분 링크로 부탁드립니다.

2023-03-26 14:53 UTC, Junghoon-P commented on src/styles/theme.tsx
> +const mode = 'dark' || 'light';
다크랑 라이트모드가 반대로 되어있던 것은 맞습니다. 이전 프로젝트 세팅을 들고와서 그렇습니다 😅 그래서 라이트모드를 기본 모드로 변경했습니다.

2023-03-26 14:53 UTC, Junghoon-P commented on src/assets/Mail.tsx
> +const Mail = () => {
좋습니다! [7bc5eba](https://github.com/In-N-Out-Dev/PortfolioHub/pull/8/commits/7bc5ebad4293aec65b65e7331ad74e8b60a9bea7) 적용했습니다~!

2023-03-26 15:31 UTC, Junghoon-P commented on src/components/Container.tsx
> +  /* background-color: ${({ theme }) => theme.colors.HIGHTLIGHT}; */
[9f999d2](https://github.com/In-N-Out-Dev/PortfolioHub/pull/8/commits/9f999d2868430ffa3e257be08855c54346910544) 반영했습니다~!

2023-03-26 21:18 UTC, somangoi commented on src/components/common/InfoCard.tsx
> +  font-family: 'Bebas Neue', cursive;
그렇군요? 저도 좀 더 알아봐야겠어영

2023-03-26 21:20 UTC, somangoi commented on src/components/Container.tsx
>  const Container = () => {
넹 좋습니다! 일단 resolve할게유

2023-03-26 21:21 UTC, somangoi approved these changes

2023-03-26 21:30 UTC, somangoi commented on src/styles/theme.tsx
> +const mode = 'dark' || 'light';
제 커밋은 요거입니다
https://github.com/In-N-Out-Dev/PortfolioHub/pull/5/commits/747a777629093ae27697c8e0622fe85aada60a83

2023-03-28 11:17 UTC, HojinAn commented on src/styles/theme.tsx
> +const mode = 'dark' || 'light';
아무래도 소미님 커밋을 반영하는 게 맞을 것 같아요!

2023-03-28 11:21 UTC, HojinAn commented on src/components/Container.tsx
>  const Container = () => {
저도 그냥 Container보다는 좀 더 분명한 이름이면 좋을 것 같아요!  
그냥 Container는 common에서 반복적으로 각 컴포넌트 등의 layout을 잡아 줄 것 같은 느낌의 네이밍이라서요

2023-03-28 11:23 UTC, HojinAn commented on src/components/common/InfoCard.tsx
> +  font-family: 'Bebas Neue', cursive;
> 특정 타이틀에서만 적용될 폰트라 오히려 app에서부터 해당 폰트를 알 필요는 없지 않을까요? `const theme = { colors, fontSize, breakPoint, };` 현재 이렇게 3가지를 theme에서 관리하고 있는데 폰트스타일 한가지를 위해 추가해야할까? 라는 고민도 있었습니다. 제안주신 부분도 고민이였긴 해서 코멘트 보고 의견 한번 더 부탁드립니다!
> 
> > ps.만일 매번 import 해서 써야하는 번거로움이 예상되신다면 타이틀용 공용 컴포넌트로 분리해도 될 것 같아요.

이런 부분으로 고민해볼 수도 있군요  
저는 단순히 그냥 theme에다 넣으면 되지 않을까 했는데, 저도 사용하고 각 담당 섹션마다 사용될 폰트니가 말씀 주신 것처럼 `타이틀용 컴포넌트`를 분리해도 좋을 것 같네요

2023-03-28 12:09 UTC, HojinAn commented on src/components/Container.tsx
>  const Container = () => {
소미님 Layout 컴포넌트 커밋 [2ff057c](https://github.com/In-N-Out-Dev/PortfolioHub/pull/5/commits/2ff057cd39e30713ee3e6e8c4940d863adf18743)과 정훈님 Container를 보건데, Container라는 이름보다는 차라리 `SectionList` 같은 이름은 어떨까요? 현재로썬 이 이름이 목적에 맞아보여서요! 바깥을 ul로 wrapping하고

2023-03-28 12:09 UTC, HojinAn commented on src/components/common/StackButton.tsx
> +  padding: 0.4rem 0.6rem;
모바일을 고려한 rem 설정 좋은 생각입니다! 저는 일단 제 임의대로 [63eafbb](https://github.com/In-N-Out-Dev/PortfolioHub/pull/9/commits/63eafbb425b82121619b4b975b8a2a24b36aecfc) 그렸는데 나중에 이거로 바꿔야 하겠네요  
이런 두께를 고려할 부분은 StackButton 밖에 없는 것 같아 저는 여기에서만 rem 적용해도 좋다고 생각합니다!

2023-03-28 12:09 UTC, HojinAn commented on src/components/introduce/Introduce.tsx
> +    <InfoCard title="INTRODUCE">
추후에 각 섹션 title도 type으로 빼는건 어떨까 조심스레 제안해봅니다..ㅎ

2023-03-28 12:09 UTC, HojinAn commented on src/components/introduce/IntroContents.tsx
> +const Wrap = styled.div`
```suggestion
const Wrap = styled.article`
```
article은 어떤가요?

2023-03-28 12:09 UTC, HojinAn commented on src/components/common/StackButton.tsx
> +    </Border>
```suggestion
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
    >
      <Border>{children}</Border>
    </a>
```
이렇게 해야 버튼 클릭할 때 링크 이동 되지 않을까요?

2023-03-29 21:27 UTC, somangoi commented
정훈님 혹시 buttons폴더 만들면 어떨까요?

2023-04-02 02:49 UTC, Junghoon-P commented on src/components/common/StackButton.tsx
> +    </Border>
[cafefb8](https://github.com/In-N-Out-Dev/PortfolioHub/pull/8/commits/cafefb810582a7f434ff41250d86bfa78f4cbe76) 반영했습니다~

2023-04-02 02:50 UTC, HojinAn approved these changes

2023-04-02 02:50 UTC, merged